export { default as Login} from './Login'
export { default as CreateAccount} from './CreateAccount'
export { default as ResetPassword} from './ResetPassword'
export { default as SetNewPd} from './SetNewPd'
export { default as RegisterAccount} from './RegisterAccount'
export { default as VerifyCode} from './VerifyCode'
//export { default as OtpVerification} from './otp'
export { default as Home} from './Home'
export { default as Edit} from './Edit'
export { default as Poll} from './Poll'

